name: "[production] Deploy to Caprover"

on:
  push:
    branches:
      - master

jobs:
  caprover-deploy:
    name: Deploy to Caprover
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Caprover
        uses: floms/action-caprover@v1
        with:
          host: "${{ secrets.CAPROVER_HOST }}"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          app: "${{ secrets.CAPROVER_APP }}"
          branch: master
